-- Oracle 12c+ sequence-backed column defaults. Run after 01_tables.sql.
-- Sample data uses explicit IDs 1-3; application-generated IDs begin at 1000.

-- Sequence names match the defaults and application SQL below.
CREATE SEQUENCE seq_vehicle_id     START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_driver_id      START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_route_id       START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_passenger_id   START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_trip_id        START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_ticket_id      START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_payment_id     START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_maintenance_id START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_feedback_id    START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE VEHICLE     MODIFY (vehicle_id DEFAULT seq_vehicle_id.NEXTVAL);
ALTER TABLE DRIVER      MODIFY (driver_id DEFAULT seq_driver_id.NEXTVAL);
ALTER TABLE ROUTE       MODIFY (route_id DEFAULT seq_route_id.NEXTVAL);
ALTER TABLE PASSENGER   MODIFY (passenger_id DEFAULT seq_passenger_id.NEXTVAL);
ALTER TABLE TRIP        MODIFY (trip_id DEFAULT seq_trip_id.NEXTVAL);
ALTER TABLE TICKET      MODIFY (ticket_id DEFAULT seq_ticket_id.NEXTVAL);
ALTER TABLE PAYMENT     MODIFY (payment_id DEFAULT seq_payment_id.NEXTVAL);
ALTER TABLE MAINTENANCE MODIFY (maintenance_id DEFAULT seq_maintenance_id.NEXTVAL);
ALTER TABLE FEEDBACK    MODIFY (feedback_id DEFAULT seq_feedback_id.NEXTVAL);
