<?php
$activePage = 'trips';
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Trips | SmartMove</title>
	<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/css/admin-panel.css"><script src="../assets/js/admin-panel.js" defer></script></head>
<body class="admin-page" data-admin-page="trips"><div class="admin-shell"><?php require __DIR__ . '/../includes/admin-sidebar.php'; ?><main class="admin-main">
	<header class="admin-topbar"><div><p class="admin-eyebrow">OPERATIONS / SCHEDULING</p><h1>Trips</h1></div><a class="admin-button admin-button-quiet" href="routes.php">Manage routes <span aria-hidden="true">→</span></a></header>
	<div class="admin-content"><section class="admin-page-intro"><div><p class="admin-eyebrow">DEPARTURE SCHEDULE</p><h2>Manage trips</h2><p>Assign a driver, vehicle, and route to each departure.</p></div><span class="admin-record-count" data-record-count>— TRIPS</span></section>
	<div class="admin-workspace admin-workspace-trip"><section class="admin-form-panel"><p class="admin-eyebrow" data-form-eyebrow>NEW TRIP</p><h2 data-form-title>Schedule a departure</h2><form data-entity-form>
		<input type="hidden" name="trip_id"><label>Route<select name="route_id" required><option value="">Loading routes…</option></select></label><div class="form-grid"><label>Vehicle<select name="vehicle_id" required><option value="">Loading vehicles…</option></select></label><label>Driver<select name="driver_id" required><option value="">Loading drivers…</option></select></label></div>
		<div class="form-grid"><label>Departure<input name="departure_time" type="datetime-local" required></label><label>Arrival<input name="arrival_time" type="datetime-local" required></label></div><div class="form-grid"><label>Fare (GHS)<input name="fare" type="number" min="0" step="0.01" required></label><label>Status<select name="status"><option>SCHEDULED</option><option>BOARDING</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>CANCELLED</option></select></label></div>
		<div class="form-actions"><button class="admin-button" type="submit" data-submit-label>Save trip</button><button class="admin-text-button" type="button" data-form-reset hidden>Cancel edit</button></div><p class="admin-form-message" data-form-message role="status" aria-live="polite"></p>
	</form></section><section class="admin-section admin-table-section"><div class="admin-section-heading"><div><p class="admin-eyebrow">ALL DEPARTURES</p><h2>Trip schedule</h2></div><button class="admin-text-button" type="button" data-refresh>Refresh</button></div><div class="admin-table-wrap"><table><thead><tr><th>Trip</th><th>Route</th><th>Vehicle / driver</th><th>Departure</th><th>Fare</th><th>Status</th><th>Actions</th></tr></thead><tbody data-entity-table><tr><td colspan="7" class="admin-empty">Loading trips…</td></tr></tbody></table></div></section></div>
	</div></main></div></body></html>
